---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: (?x)(
          aopy/a|
          tests/a
          )
      - id: ruff-format
        exclude: (?x)(
          aopy/a|
          tests/a
          )
  - repo: local
    hooks:
      - id: pyre
        name: Pyre
        entry: poetry run pyre check
        language: system
        types: ['python']
        pass_filenames: false
      - id: unittests
        name: Unit Tests
        entry: poetry run python -m unittest
        language: system
        types: ['python']
        exclude: (?x)(
          aopy/a|
          tests/a
          )
